### PR TITLE
Add compatibility badges

### PR DESCRIPTION
**Pull request by zkline101**
[Here](https://github.com/Esri/arcgis-maps-sdk-swift/blob/zach/addBadges/README.md) is what it looks like.

Swift issue #6362

### CODE REVIEW

**Comment by saratchandrakarumuri** [comment]
Should we be adding macOS too since we support mac catalyst or since it is not native macOS it is not required?

**Comment by zkline101** [comment]
> Should we be adding macOS too since we support mac catalyst or since it is not native macOS it is not required?

I noticed that too and was assuming the same thing. Since it isn't native macOS it wasn't listed. But I can see if I can get some clarity on that.

**Review by philium — APPROVED** [review]

**Comment by philium** [comment]
There was a discussion about it in [an issue](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1269) in 2021.

**Comment by zkline101** [comment]
Thanks for pointing that out! I searched "mac catalyst" in the issues and not even that issue showed up.

**Review by saratchandrakarumuri — APPROVED** [review]

**Pull request merged**
